[project]
name = "calibre-helpers"
version = "0.1"
description = "Scripts to help me manage my Calibre library"
readme = "README.md"
authors = [{name = "Rae Knowler"}]
license = "Apache-2.0"
requires-python = ">=3.14"
classifiers = []
dependencies = [
    "certifi",
    "click",
    "pdf2doi",
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.scripts]
calibre-helpers = "cli:cli"

[project.optional-dependencies]
dev = ["black", "isort"]

[tool.isort]
profile = "black"
known_first_party = "metadata"

[tool.black]
line-length = 88
